version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: reddit_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reddit_clone
    ports:
      - "5433:5432"
    volumes:
      - reddit_pg_data:/var/lib/postgresql/data

volumes:
  reddit_pg_data:
